title: Mi blog desde cero
email: lgarciavelazquez@educantabria.es
baseurl: /myblog4
url: https://lgarciavelazquez.github.io
repository: lgarciavelazquez/myblog4
collections:
  authors:
    output: true
    #permalink: /:collection/:title
    permalink: /:collection/:title
  pages:
    output: true   
  posts:
     output: true
     permalink: /blog/:name   

defaults:
    - scope:
        path: ""
        type: "authors"
      values:
         layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
         layout: "post"                
    - scope:
        path: ""
      values:
         layout: "default" 

plugins:
   - jekyll-feed
   - jekyll-sitemap
   - jekyll-seo-tag       